base:
  random_state: 42

preprocessing:
  raw_data_dir: /Users/allenchen/projects/baseball-analytics/data/raw/
  agg_data_filepath: /Users/allenchen/projects/baseball-analytics/data/aggregated/20230504_agg_raw_data.csv
  dataset_filepath: /Users/allenchen/projects/baseball-analytics/data/training/20230504_features_and_targets.csv
  training_data_start_date: "2008-02-27"
  training_data_end_date: "2023-05-11"

splitting:
  dataset_filepath: /Users/allenchen/projects/baseball-analytics/data/training/20230504_features_and_targets.csv
  train_filepath: /Users/allenchen/projects/baseball-analytics/data/training/20230504_train.csv
  val_filepath: /Users/allenchen/projects/baseball-analytics/data/training/20230504_val.csv
  test_size: 0.2

training:
  epochs: 10
  batch_size: 32
  lr: 0.001

saving:
  saved_metrics_filepath: /Users/allenchen/projects/baseball-analytics/results/metrics_001.json
  saved_model_filepath: /Users/allenchen/projects/baseball-analytics/results/model_001.pt
