base:
  random_state: 42

preprocessing:
  raw_data_dir: /Users/allenchen/projects/baseball-analytics/data/raw/
  raw_data_filepath: /Users/allenchen/projects/baseball-analytics/data/aggregated/20230504_agg_raw_data.csv
  dataset_filepath: /Users/allenchen/projects/baseball-analytics/data/20230505_features_and_targets.csv
  raw_data_starting_date: "2008-02-27"

splitting:
  dataset_filepath: /Users/allenchen/projects/baseball-analytics/data/20230505_features_and_targets.csv
  train_filepath: /Users/allenchen/projects/baseball-analytics/data/20230505_train.csv
  val_filepath: /Users/allenchen/projects/baseball-analytics/data/20230505_val.csv
  test_size: 0.2

training:
  epochs: 10
  batch_size: 32
  lr: 0.001

saving:
  saved_metrics_filepath: /Users/allenchen/projects/baseball-analytics/results/metrics_001.json
  saved_model_filepath: /Users/allenchen/projects/baseball-analytics/results/model_001.pt
